// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDarr2-Kf_XKunr0mooUGZf3Y5FPtQQlYU',
    appId: '1:685122223165:web:48ff74bf66a37720353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    authDomain: 'unibuddy-785ab.firebaseapp.com',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
    measurementId: 'G-Q5WKSD0ML3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC43QLD3VwrYmyBRXe2k-RYkEnaeBs6_34',
    appId: '1:685122223165:android:7399bea0fc73c249353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOzBGk6Ta86f3EPger7e8uCNmbPrUC8BY',
    appId: '1:685122223165:ios:69e9812585bd03cd353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
    iosClientId: '685122223165-r4678osg2bolh62r7b44k0ict82pp86o.apps.googleusercontent.com',
    iosBundleId: 'com.example.unibuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOzBGk6Ta86f3EPger7e8uCNmbPrUC8BY',
    appId: '1:685122223165:ios:69e9812585bd03cd353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
    iosClientId: '685122223165-r4678osg2bolh62r7b44k0ict82pp86o.apps.googleusercontent.com',
    iosBundleId: 'com.example.unibuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDarr2-Kf_XKunr0mooUGZf3Y5FPtQQlYU',
    appId: '1:685122223165:web:74fa5ea8e90ffecf353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    authDomain: 'unibuddy-785ab.firebaseapp.com',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
    measurementId: 'G-DVC6B4YL0T',
  );
}
