// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDarr2-Kf_XKunr0mooUGZf3Y5FPtQQlYU',
    appId: '1:685122223165:android:48ff74bf66a37720353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarr2-Kf_XKunr0mooUGZf3Y5FPtQQlYU',
    appId: '1:685122223165:ios:48ff74bf66a37720353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
    iosBundleId: 'com.example.unibuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarr2-Kf_XKunr0mooUGZf3Y5FPtQQlYU',
    appId: '1:685122223165:macos:48ff74bf66a37720353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
    iosBundleId: 'com.example.unibuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDarr2-Kf_XKunr0mooUGZf3Y5FPtQQlYU',
    appId: '1:685122223165:web:48ff74bf66a37720353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDarr2-Kf_XKunr0mooUGZf3Y5FPtQQlYU',
    appId: '1:685122223165:web:48ff74bf66a37720353e54',
    messagingSenderId: '685122223165',
    projectId: 'unibuddy-785ab',
    storageBucket: 'unibuddy-785ab.firebasestorage.app',
    authDomain: 'unibuddy-785ab.firebaseapp.com',
    measurementId: 'G-Q5WKSD0ML3',
  );
}
